version: 2
updates:
  - package-ecosystem: maven
    directory: /services/mapping-studio-api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /services/webhook-receiver
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /services/canonbridge-mock
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /services/transformer
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
