apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources for the canonbridge namespace
namespace: canonbridge

resources:
  - namespace.yaml
  - configmap.yaml
  - network-policies.yaml
  - postgres-statefulset.yaml
  - kafka-statefulset.yaml
  - business-service-deployment.yaml
  - otel-collector.yaml
  - transformer/

commonLabels:
  app.kubernetes.io/part-of: canonbridge
  app.kubernetes.io/managed-by: kustomize
