-- Ensure FoodMarket exists as a first-class mock-backed system template.
-- Earlier migrations adjusted this connection id, but no migration created it.

INSERT INTO etl_outbound_connections (
    connection_id,
    tenant_id,
    draft_id,
    name,
    purpose,
    protocol,
    method,
    url,
    credential_id,
    environment,
    timeout_ms,
    status,
    last_test_at,
    last_test_result,
    retry_policy,
    response_handling,
    is_system_template,
    base_url,
    known_endpoints,
    created_at,
    updated_at
) VALUES (
    'f7777777-7777-7777-7777-777777777777'::uuid,
    'tenant-acme',
    NULL,
    'FoodMarket Order System',
    'SOURCE_PAYLOAD',
    'REST',
    'GET',
    'http://canonbridge-mock:8080/api/foodmarket/orders/FM-1001',
    'f7000000-7777-7777-7777-000000000001'::uuid,
    'SANDBOX',
    5000,
    'HEALTHY',
    NOW(),
    '{"statusCode": 200, "durationMs": 180, "success": true}'::text,
    '{"maxAttempts": 3, "backoff": "exponential", "retryableStatuses": [429, 503, 504]}'::jsonb,
    '{"successField": "order", "errorField": "error"}'::jsonb,
    TRUE,
    'http://canonbridge-mock:8080',
    '[
        {"path": "/api/foodmarket/orders/{orderId}", "method": "GET", "description": "Get order by ID"},
        {"path": "/api/foodmarket/orders", "method": "GET", "description": "List orders"}
    ]'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT (connection_id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    draft_id = EXCLUDED.draft_id,
    name = EXCLUDED.name,
    purpose = EXCLUDED.purpose,
    protocol = EXCLUDED.protocol,
    method = EXCLUDED.method,
    url = EXCLUDED.url,
    credential_id = EXCLUDED.credential_id,
    environment = EXCLUDED.environment,
    timeout_ms = EXCLUDED.timeout_ms,
    status = EXCLUDED.status,
    last_test_at = EXCLUDED.last_test_at,
    last_test_result = EXCLUDED.last_test_result,
    retry_policy = EXCLUDED.retry_policy,
    response_handling = EXCLUDED.response_handling,
    is_system_template = EXCLUDED.is_system_template,
    base_url = EXCLUDED.base_url,
    known_endpoints = EXCLUDED.known_endpoints,
    updated_at = NOW();
