global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: canonbridge-transformer
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:3000
        labels:
          service: transformer

  - job_name: canonbridge-business-service
    metrics_path: /q/metrics
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          service: business-service
