apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: canonbridge

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - poddisruptionbudget.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: transformer
  app.kubernetes.io/component: data-transformation
  app.kubernetes.io/part-of: canonbridge

images:
  - name: canonbridge/transformer
    newTag: latest
