apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: transformer-pdb
  namespace: canonbridge
  labels:
    app: transformer
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: transformer
  unhealthyPodEvictionPolicy: AlwaysAllow
